### ISSUE TITLE
Extend to other languages - C++

### ISSUE THREAD

**Issue by mingboiz** [RobYang1024/OCaMOSS#4]
Hey there, love the work! I would like to fork - extending to C++ specifically and I was wondering if it's possible to give me some general directions on how I may do that? Thank you!

**Comment by yangdanny97** [comment]
I think you just need to add a json file under language_files containing the cpp keywords, and then add an entry for .cpp extension in preprocessing.ml

**Comment by mingboiz** [comment]
not sure if you guys are accepting contributions but thank you very much for pointing out the direction to me, happy to close this issue if you prefer that!
